### ISSUE TITLE
Flag to run `cargo +nightly`

### ISSUE THREAD

**Issue by julioolvr** [dflemstr/rust-native-wasm-loader#1]
Since `wasm32-unknown-unknown` is available on Rust nightly only right now, what do you think about adding a configuration flag to run Cargo on nightly regardless of `rustup`'s default config? Something like

```
cargo +nightly build ...
```

Or maybe there's another way to make it work without `rustup default nightly` that I'm not aware of?

I don't mind sending a PR if you like the idea 👍

**Comment by dflemstr** [comment]
I check in the right version of Rust to use into the source repository by using a [toolchain file](https://github.com/rust-lang-nursery/rustup.rs#the-toolchain-file)!  If this doesn't meet your needs feel free to create a PR!

**Comment by julioolvr** [comment]
Oh I didn't know about that 😅 It's perfect for my use-case so I'll just go ahead and close this issue. Thanks!
