### ISSUE TITLE
Errors seem to not be correctly propagated

### ISSUE THREAD

**Issue by akatechis** [dflemstr/rust-native-wasm-loader#14]
I incorrectly moved my lib.rs file (for the "simple version" I was trying out), but when I ran it, rather than getting cargo's error (which turned out to be something to the effect of "Cannot parse manifest..." it gives the error below.

Stack:
```
ERROR in ./src/datastore/lib.rs
Module build failed: TypeError: Cannot read property 'slice' of undefined
    at F:\workspace\project\node_modules\rust-native-wasm-loader\dist\index.js:253:30
    at Generator.next (<anonymous>)
    at step (F:\workspace\project\node_modules\rust-native-wasm-loader\dist\index.js:30:191)
    at F:\workspace\project\node_modules\rust-native-wasm-loader\dist\index.js:30:437
    at new Promise (<anonymous>)
    at F:\workspace\project\node_modules\rust-native-wasm-loader\dist\index.js:30:99
    at handleCargo (F:\workspace\project\node_modules\rust-native-wasm-loader\dist\index.js:267:18)
    at F:\workspace\project\node_modules\rust-native-wasm-loader\dist\index.js:156:40
    at Generator.next (<anonymous>)
    at step (F:\workspace\project\node_modules\rust-native-wasm-loader\dist\index.js:30:191)
    at F:\workspace\project\node_modules\rust-native-wasm-loader\dist\index.js:30:361
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
 @ ./src/index.js 1:0-41 3:0-7
```

I'm on Windows 10, using the following:

`rustc 1.24.0 (4d90ac38c 2018-02-12)`
`cargo 0.25.0 (8c93e0895 2018-02-01)`
`node v9.7.1`
`npm v5.6.0`

And the following dependencies in `package.json`:

```
    "rust-native-wasm-loader": "^0.6.5",
    "wasm-loader": "^1.3.0",
    "webpack": "^4.0.1",
    "webpack-cli": "^2.0.10",
    "webpack-serve": "^0.1.4"
```

**Comment by akatechis** [comment]
When I step through the compilation process, if I inspect the `result` inside of `handleCargo`'s generator function, I see that the for loop assumes `result.stdout` has all the output.

I suppose the fix for this would be to check `result.code` and `result.stderr`. I wouldn't mind creating a PR for this, if you like. It seems like a simple enough fix?

**Comment by dflemstr** [comment]
Sounds like a reasonable fix! Please send a PR :)

**Comment by melloc01** [comment]
@akatechis did you manage to get it to work?

**Comment by akatechis** [comment]
Yes, I opened the PR, and then got sidetracked by some other stuff. Will return to this tonight (when I get home from work). Apologies for the delay :)
