### ISSUE TITLE
wasm2es6js looking for non-existent file

### ISSUE THREAD

**Issue by mneil** [dflemstr/rust-native-wasm-loader#15]
```
ERROR in ./src/main.rs
Module build failed: Error: Command failed: wasm2es6js target\wasm32-unknown-unknown\release\garuda-wasm-mdns_wasm.wasm -o target\wasm32-unknown-unknown\release\garuda-wasm-mdns_wasm.js --base64
thread 'main' panicked at 'failed to open input: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', libcore\result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

The wasm2es6js command is looking for `garuda-wasm-mdns_wasm.wasm` which is non-existent. The file that does exist is `garuda-wasm-mdns.wasm`. Somewhere there must be a descrepency between naming the release file and what wasm2es6js is looking for.

rustc 1.26.0-nightly (2789b067d 2018-03-06)
wasm-bindgen 0.1.1

Webpack config
```
rules: [
      {
        test: /\.rs$/,
        use: [{
          loader: 'wasm-loader',
        }, {
          loader: 'rust-native-wasm-loader',
          options: {
            release: true,
            gc: true,
            wasmBindgen: true,
            wasm2es6js: true,
          },
        }],
      }
    ],
```

**Comment by greenpdx** [comment]
I am having a similar problem. If I do not add wasm2es6js un the options I get
```
This relative module was not found:

* ./fullwasm_bg in ./src/lib.rs
 
```
in the target/wasm32-unknown-unknown/release directory
I see the .d, .js, .wasm and the _bg.wasm files.

Has wasmBindgen changed the _wasm to _bg?

**Comment by greenpdx** [comment]
I changed all _wasm to _bg and added wasm2es6: true and it sometimes works. I still get an error it I do not add wasm2es6
```
This relative module was not found:

* ../target/wasm32-unknown-unknown/release/fullwasm_bg in ./src/lib.rs
 ```
Sometimes when I run I get, but other time I do not. Working on it
TypeError: wasm is undefined
