### ISSUE TITLE
add debug option to wasmBindgen

### ISSUE THREAD

**Issue by greenpdx** [dflemstr/rust-native-wasm-loader#16]
wasn-bindgen has a debug flag, It would be nice to add it to the build

**Comment by dflemstr** [comment]
@greenpdx How would you prefer this to look?

**Comment by greenpdx** [comment]
Have a flag for wasmBindgen debug: false ( default).  When true the wasn-bindgen --debug is added.  Also I would like the cargo to add --verbose?
