### ISSUE TITLE
Add an example project

### ISSUE THREAD

**Issue by koute** [dflemstr/rust-native-wasm-loader#2]
For someone like me whose experience with webpack is quite limited it would be nice to have an already made hello-world-style example project which I could just run and poke at.

**Comment by dflemstr** [comment]
I added one simple example with raw wasm: https://github.com/dflemstr/rust-native-wasm-loader/tree/master/examples/simple

And another example with a full-blown integration of stdweb and html bundling: https://github.com/dflemstr/rust-native-wasm-loader/tree/master/examples/advanced-stdweb

**Comment by koute** [comment]
Thanks! I'll be sure to play with it this week.
