### ISSUE TITLE
Build dependencies with whitespace in their path are not properly handled

### ISSUE THREAD

**Issue by grind086** [dflemstr/rust-native-wasm-loader#24]
Build dependencies are currently being parsed using the following line:

https://github.com/dflemstr/rust-native-wasm-loader/blob/03a6e58fb23ca3e64904b647225e4b04af1ccb83/src/cargo.js#L77

This will fail if a space exists anywhere in a dependency path. For example, if you have a dependency file that contains something like this:

```text
C:\Users\User\ Name\Documents\project\target\wasm32-unknown-unknown\debug\rust.wasm: C:\Users\User\ Name\Documents\project\src\mod.rs C:\Users\User\ Name\Documents\project\src\lib.rs
```

You wind up trying to add each of the following lines as a dependency:

```text
C:\Users\User
Name\Documents\project\src\mod.rs
C:\Users\User
Name\Documents\project\src\lib.rs
```

Fixing this is a little tricky, since JavaScript regex doesn't support negative lookbehind. My current solution is to reverse the string, and use a negative lookahead instead:

```javascript
const reverseString = str => str.split('').reverse().join('');

const parseDependencies = str =>
    reverseString(str.split(/:\s+/)[1].trim())
        .split(/(?:\s(?!\\))+/)
        .map(reverseString);
```

which correctly parses the above example into

```text
C:\Users\User Name\Documents\project\src\mod.rs
C:\Users\User Name\Documents\project\src\lib.rs
```

Is that sufficient? Or am I missing a better solution?

**Comment by grind086** [comment]
Also I noticed checking for the existence of `wasmFile` is done in three separate places instead of in `handleCargo()` - but it won't ever reach those because on the following line:

https://github.com/dflemstr/rust-native-wasm-loader/blob/03a6e58fb23ca3e64904b647225e4b04af1ccb83/src/cargo.js#L73

it's already assumed to be a string. If it's not found a `TypeError` will be thrown here. I'd suggest checking just above that point, and using something more robust like

```javascript
const depFile = path.format({ ...path.parse(wasmFile), ext: 'd' });
```

I can get a PR rolling with all (or some) of these changes, I just wanted some input on the whitespace problem first.

**Comment by RobertBorg** [comment]
I've looked at the whitespace problem and your proposed solution sound good to me.

Another solution would be to manually check last char in path strings and rejoin those ending with \ with the next one. I think i prefer your solution.

WDYT @dflemstr  ?

**Comment by dflemstr** [comment]
How does this work with UNIX-like file systems (Mac and Linux) which probably represent the majority of users?

Also, this is in general unsolvable by only looking at the text.  Here are some valid file paths, for example:

```
# Windows:
c:\foo\bar baz\quuz c:\hello
→ parts: ["c:", "foo", "bar baz", "quuz c:", "hello"]
# UNIX:
/c:\foo\bar baz\quuz/hello/ c:\foo /bar
→ parts: ["c:\foo\bar baz\quuz", "hello", " c:\foo ", "bar"]
```

I think the only reliable way to fix this problem is to try joining the paths and check if the resulting file exists.

**Comment by grind086** [comment]
Those are definitely valid paths, but we only need to worry about rust's dependency file which explicitly adds a `\` before spaces in paths. See [here](https://github.com/rust-lang/cargo/blob/9d57564a62360a9b637d3c45d919b7d08d59fead/src/cargo/core/compiler/output_depinfo.rs#L22):

```rust
fn render_filename<P: AsRef<Path>>(path: P, basedir: Option<&str>) -> CargoResult<String> {
    let path = path.as_ref();
    let relpath = match basedir {
        None => path,
        Some(base) => match path.strip_prefix(base) {
            Ok(relpath) => relpath,
            _ => path,
        },
    };
    relpath
        .to_str()
        .ok_or_else(|| internal("path not utf-8"))
        .map(|f| f.replace(" ", "\\ "))
}
```

**Comment by dflemstr** [comment]
Aha, apologies for totally missing that! Makes sense, this seems to be the way to go.
