### ISSUE TITLE
Failed to build using npm, but looks ok using same command in CLI

### ISSUE THREAD

**Issue by greenpdx** [dflemstr/rust-native-wasm-loader#5]
I am try to use rust-native-wasm-loader with vue-cli.  I am still new at webpack and vue adds a layer between webpack configuration and the development.

First I have to add webpack configuration using chainWebpack. So my configuration looks like this
``` 
  chainWebpack: webpackConfig => {
    webpackConfig.module
     .rule('wasm')
       .test(/\.wasm$/)
       .use('wasm-loader')
       .loader('wasm-loader'),
    webpackConfig.module
     .rule('rust')
       .test(/\.rs$/)
       .use('rust-native-wasm-loader')
       .loader('rust-native-wasm-loader')
       .options({
         gc: true,
          release: true
       })
  },
```
Then when I build using npm run serve I get this error
"""
 15% building modules 45/46 modules 1 active ...-19-0!/home/ubuntu/vuerust/src/l 94% asset optimization                     

 ERROR  Failed to compile with 1 errors                                 13:10:14

 error  in ./src/lib.rs

Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)

 @ ./src/main.js 7:0-28
 @ multi (webpack)-dev-server/client?http://localhost:8080/ (webpack)/hot/dev-server.js ./src/main.js
"""
The artifacts are 
drwxrwxr-x 3 ubuntu ubuntu  4096 Feb  9 13:09 build
drwxrwxr-x 2 ubuntu ubuntu  4096 Feb  9 13:10 deps
drwxrwxr-x 2 ubuntu ubuntu  4096 Feb  9 13:09 examples
drwxrwxr-x 2 ubuntu ubuntu  4096 Feb  9 13:09 incremental
drwxrwxr-x 2 ubuntu ubuntu  4096 Feb  9 13:09 native
-rw-rw-r-- 1 ubuntu ubuntu   137 Feb  9 13:10 vuerust.d
-rw-rw-r-- 1 ubuntu ubuntu 39938 Feb  9 13:10 vuerust.gc.wasm
-rw-rw-r-- 2 ubuntu ubuntu 57409 Feb  9 13:10 vuerust.wasm

Now here is the interesting part. When I run the command 
```
cargo web build --message-format=json --target=wasm32-unknown-unknown --release > log
```
I get a good build with artifact 
drwxrwxr-x 3 ubuntu ubuntu  4096 Feb  9 13:13 build
drwxrwxr-x 2 ubuntu ubuntu  4096 Feb  9 13:14 deps
drwxrwxr-x 2 ubuntu ubuntu  4096 Feb  9 13:13 examples
drwxrwxr-x 2 ubuntu ubuntu  4096 Feb  9 13:13 incremental
drwxrwxr-x 2 ubuntu ubuntu  4096 Feb  9 13:13 native
-rw-rw-r-- 1 ubuntu ubuntu   137 Feb  9 13:14 vuerust.d
-rw-rw-r-- 1 ubuntu ubuntu 17040 Feb  9 13:14 vuerust.js
-rw-rw-r-- 2 ubuntu ubuntu 42167 Feb  9 13:14 vuerust.wasm

If you tell me how to debug webpack I can do that, What I do not understand is the .js file is missing when using npm build and the sizes are different.

**Comment by dflemstr** [comment]
It looks like you didn't enable `cargo-web` support.  See the bottom of the README of this library!

**Comment by greenpdx** [comment]
That works, thank you. I am impressed with your es6 knowledge. Now I have general es6 question.  All the examples I see 
```
loadWasm.then(module => {
  console.log('return value was', module.add(2, 3));
  this.module = module   // can I do this? will this increase the lifetime? 
});
```
Is the a way to create it more like a library, where I would be able to load the wasm, create an instance and then use it in the else where in the Vue component?  Vue has  watch statement that detects changes that I could use as a trigger. 
 
I notice you use the, where can I get more information about this?
```
const varName = async function(params) {
   return value
} 
```
I will close this now , but I would like to continue this thread.

**Comment by greenpdx** [comment]
New problem,  The module being returned is just an empty object {}

**Comment by greenpdx** [comment]
With enough work I can fin the issue, but I would still like some help with the Vue interface.
