### ISSUE TITLE
Error parsing JSON

### ISSUE THREAD

**Issue by Nighink** [dflemstr/rust-native-wasm-loader#7]
I tried the loader with a Rust project that uses some other libraries and got a failure on `yarn run webpack` saying:
```
ERROR in ./src/lib.rs
Module build failed: SyntaxError: Unexpected token { in JSON at position 558
    at JSON.parse (<anonymous>)
    at handleCargo (<path>\node_modules\rust-native-wasm-loader\dist\index.js:142:23)
```

I got it to work by subsituting `"\n"` instead of `_os2.default.EOL` in the index.js file at line 142. I assume, it is a Windows problem where the normal newline is expected to be `\r\n` but the incoming data seems to just use `\n`.

I am using yarn 1.3.2 with rustc 1.25.0-nightly (2018-02-08) on Windows 10.

**Comment by dflemstr** [comment]
Curious how cargo still uses `\n` for its output on Windows.  Feel free to send a PR with the expected behavior!
